image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-card-delivey.jar &

build_script:
  - ./gradlew test --info "-Dselenide.headless=true"
